### ISSUE TITLE
Glean Ping View shouldn't fail if the metric is not present in BQ yet

### ISSUE THREAD

**Issue by fbertsch** [mozilla/lookml-generator#100]
On 5/11, the lookml-generator [failed when a metric was not yet available in the BQ schema](https://bugzilla.mozilla.org/show_bug.cgi?id=1710871). While we're working on another path to ensure lookml-generator runs only after schema deploys succeed, we should in the meantime be robust to that condition. If a metric is not present, we should log and move on to the next.

**Comment by jklukas** [comment]
Note that we do this sort of existence check when generating views by pulling down the schemas tarball associated with the deployed tables: https://github.com/mozilla/bigquery-etl/blob/a081bf22b53c9f103528526d9c4270270c9f226f/bigquery_etl/view/generate_stable_views.py#L278-L288

In that case, we're only checking for existence of tables, but one could walk the JSON schema to discover metrics as well.
