### ISSUE TITLE
Include Glean Ping descriptions in generated LookML

### ISSUE THREAD

**Issue by fbertsch** [mozilla/lookml-generator#106]
Looker Explores have an [optional description field](https://docs.looker.com/reference/explore-params/description-for-explore) that displays as a tooltip next to the explore in the drop-down. For Glean Ping explores, we should enable that tooltip by pulling in the description through the probe-info-service [/pings endpoint](https://probeinfo.telemetry.mozilla.org/glean/fenix/pings). For example, the activation ping for Fenix explore would have the description `This ping is intended to provide a measure of the activation of mobile\nproducts. It's generated when Fenix starts, right after Glean is\ninitialized. It doesn't include the client_id, since it might be reporting\nan hashed version of the Google Advertising ID.`.

**Comment by wlach** [comment]
This would also be useful for https://github.com/mozilla/glean-dictionary/issues/605

**Comment by wlach** [comment]
On second thought, I wonder if pulling a description for the ping is the right thing here. I wonder if we should just say something like "Looker explore for the <foo> ping" -- IMO we should be directing people to the Glean Dictionary for getting detailed information on pings, where we can provide much more context.

**Comment by fbertsch** [comment]
The problem is there is no good way to link directly there from the explores. It's important that we surface information about data inside Looker, when possible.

**Comment by wlach** [comment]
> The problem is there is no good way to link directly there from the explores. It's important that we surface information about data inside Looker, when possible.

I understand the sentiment, but ping descriptions are rather long and technical and Looker doesn't really provide a good context for interpreting them (since it has no concept of what a ping really is). At the very least, I would suggest prefixing the ping description with my suggested wording: "Looker explore for the `<foo>` ping".

**Comment by fbertsch** [comment]
> At the very least, I would suggest prefixing the ping description with my suggested wording: "Looker explore for the `<foo>` ping".

That seems fine to me. I'm not sure how necessary the "Looker explore" part is since they're only viewable in Looker while looking at the explores dropdown, but it's not a big deal either way.

**Comment by wlach** [comment]
> That seems fine to me. I'm not sure how necessary the "Looker explore" part is since they're only viewable in Looker while looking at the explores dropdown, but it's not a big deal either way.

Hmm, yeah, we can at least drop the "Looker" part of that. 😄 

As I mention above, I think we may also want to surface a link to these explores from the Glean Dictionary (but even there I'm pretty sure the "Looker" part will be obvious).

**Comment by fbertsch** [comment]
> As I mention above, I think we may also want to surface a link to these explores from the Glean Dictionary (but even there I'm pretty sure the "Looker" part will be obvious).

Oh, I see, I didn't understand that you would be parsing LookML and using the description as well. Wouldn't it be easier to build the URL and label it as a link to the explore? Do you need this description?

**Comment by wlach** [comment]
> Oh, I see, I didn't understand that you would be parsing LookML and using the description as well. Wouldn't it be easier to build the URL and label it as a link to the explore? Do you need this description?

So what I'm thinking is that we should link out to all the explores under a namespace, under a "Looker explores" tab or similar under the application. In that case I think it would be easier to just pull the description from the namespaces file (and whatever other public data sources we're using), so we can just treat all the explores uniformly:

![image](https://user-images.githubusercontent.com/20569/119154052-cd891e00-ba1f-11eb-8c34-00f1ce848ae2.png)

**Comment by fbertsch** [comment]
Okay, got it! We were definitely talking past each other, but I think I understand now. This issue was originally for adding descriptions to the generated LookML, but you also want to surface those in the `namespaces.yaml`, so that the Glean Dictionary can use them. For that reason, they need to be a bit more generalized than just what people might see in Looker. Is that right?

**Comment by wlach** [comment]
> Okay, got it! We were definitely talking past each other, but I think I understand now. This issue was originally for adding descriptions to the generated LookML, but you also want to surface those in the `namespaces.yaml`, so that the Glean Dictionary can use them. For that reason, they need to be a bit more generalized than just what people might see in Looker. Is that right?

That's right, yes. I guess we're really talking about two different features -- although one will affect the other, so IMO it makes sense to talk about them together. My understanding of this is still evolving-- it's possible that we might ultimately need to teach the glean dictionary to parse the generated LookML to generate a full list of explores for display (since not all explores are published in namespaces.yaml).

**Comment by fbertsch** [comment]
> That's right, yes. I guess we're really talking about two different features -- although one will affect the other, so IMO it makes sense to talk about them together. My understanding of this is still evolving-- it's possible that we might ultimately need to teach the glean dictionary to parse the generated LookML to generate a full list of explores for display (since not all explores are published in namespaces.yaml).

That will get real tricky - then we'd need to parse LookML, LookML SQL (which has parameters), and SQL in bigquery-etl to understand which underlying tables are being used and which fields are being selected. I'm not sure how necessary it is either since we're looking to support autogenerated aggregates and ping-level tables, all of which are present in lookml-generator.

**Comment by wlach** [comment]
I'm interested in working on this one, I assume nobody's going to object. Will get to it later this week.
