### ISSUE TITLE
Some Glean pings are missing their metrics

### ISSUE THREAD

**Issue by fbertsch** [mozilla/lookml-generator#160]
The Credit Cards Sync ping has a few metrics. One is a counter [(outgoing batches)](https://dictionary.telemetry.mozilla.org/apps/fenix/metrics/creditcards_sync_outgoing_batches). However, following the link in the Glean Dictionary, the Looker dashboard is empty: https://mozilla.cloud.looker.com/explore/fenix/creditcards_sync?qid=YtzyGcDHQaMGfZ6WFyPq2O&toggle=vis

That explore doesn't show any metrics available at all, just some generic info from the Glean Ping itself. Clearly the metrics are not flowing through correctly. We would expect to see a few non-default Glean fields present in this explore.

**Comment by wlach** [comment]
Noticed this with the addresses sync ping as well: https://dictionary.telemetry.mozilla.org/apps/fenix/pings/addresses-sync?showExpired=1

A bunch of labeled counters should be showing up, but aren't: https://mozilla.cloud.looker.com/explore/fenix/addresses_sync?qid=bFbDinnoIiBicVDamCWJrp
