### ISSUE TITLE
Funnel analysis yields false negatives in some cases

### ISSUE THREAD

**Issue by wlach** [mozilla/lookml-generator#281]
In implementing #278, I found <strike>a few</strike> one edge case where the funnel analysis explore would falsely match an event <strike>or falsely *not* match an event</strike>. I don't think they will materially affect any analysis at this point, but we should probably still fix them.

## Case 1: False negative - Multiple event properties before event index

Our current regular expression only matches an event property index before the actual event definition.
This can be a problem if there are multiple event properties, there might be another between the first and the second property, and thus the regex won't match.

Here's a quick query which demonstrates the problem for the [collections saved](https://dictionary.telemetry.mozilla.org/apps/fenix/metrics/collections_saved) event on Fenix:

```sql
WITH
  step_1 AS (
  SELECT
    CONCAT("(?:", ARRAY_TO_STRING(ARRAY_AGG(CONCAT(mozfun.event_analysis.escape_metachars(properties_value.value), mozfun.event_analysis.escape_metachars(e.INDEX))),'|'), ')(?:,|$)') AS match_string1,
    CONCAT("(?:", ARRAY_TO_STRING(ARRAY_AGG(CONCAT(mozfun.event_analysis.escape_metachars(properties_value.value), '[^,]*', mozfun.event_analysis.escape_metachars(e.INDEX))),'|'), ')(?:,|$)') AS match_string2
  FROM
    `mozdata.fenix.event_types` AS e
  CROSS JOIN
    UNNEST(event_properties) AS properties
  CROSS JOIN
    UNNEST(properties.value) AS properties_value
  WHERE
    (category = 'collections')
    AND (event = 'saved')
  AND (properties.key = 'tabs_open')
  AND (properties_value.key = '1')
)
SELECT
    funnel_analysis.events
FROM
  `mozdata.fenix.events_daily` AS funnel_analysis
CROSS JOIN
  step_1
WHERE
  funnel_analysis.submission_date = DATE('2021-10-10')     AND sample_id = 0
  AND not REGEXP_CONTAINS(funnel_analysis.events, step_1.match_string1)
    AND REGEXP_CONTAINS(funnel_analysis.events, step_1.match_string2)
LIMIT
  500
```

Here we have two regular expressions: the current one (which only matches the property value and event value) and one that will match the property value *followed by any other property value* and then the event value. Running this, we see one row which is not matched by the first. Digging in we see the following unicode sequence in the event sequence for that day:

`[0004] [0006] s`

`[0004]` matches the event property index for "1 tab open", but it's followed by `[0006]` (which corresponds to some value for the "tab selected" property).

I suspect this hasn't been terribly common so far, but we should fix it. I believe all we should need to do is add a `'[^,]*'` matcher between the event property and the event (a `,` always indicates the end of an event, so we don't want to allow it in between).

## Case 2: False positive - matching inside other events

(this is actually incorrect, the query below should be using the [event_index_to_match_string UDF](https://github.com/mozilla/bigquery-etl/blob/main/sql/mozfun/event_analysis/event_index_to_match_string/udf.sql), which adds a comma, but isn't -- the SQL generated by lookml-generator doesn't suffer from this problem)

<strike>
A similar problem is where we think we matched an event sequence, when it was actually only a subsequence inside another sequence.
For example, this query turns up 16 false positives that we'd get with the current system:

```sql
WITH
  step_1 AS (
  SELECT
    CONCAT("(?:", ARRAY_TO_STRING(ARRAY_AGG(CONCAT(mozfun.event_analysis.escape_metachars(properties_value.value), '[^,]*', mozfun.event_analysis.escape_metachars(e.INDEX))),'|'), ')(?:,|$)') AS match_string1,
    CONCAT("(?:", ARRAY_TO_STRING(ARRAY_AGG(CONCAT(mozfun.event_analysis.escape_metachars(properties_value.value), '[^,]*', mozfun.event_analysis.escape_metachars(e.INDEX))),'|'), ')') AS match_string2
  FROM
    `mozdata.fenix.event_types` AS e
  CROSS JOIN
    UNNEST(event_properties) AS properties
  CROSS JOIN
    UNNEST(properties.value) AS properties_value
  WHERE
    (category = 'collections')
    AND (event = 'saved')
    AND (properties.key = 'tabs_open')
    AND (properties_value.key = '1') )
SELECT
  funnel_analysis.events
FROM
  `mozdata.fenix.events_daily` AS funnel_analysis
CROSS JOIN
  step_1
WHERE
  funnel_analysis.submission_date = DATE('2021-10-10')
  AND sample_id = 0
  AND NOT REGEXP_CONTAINS(funnel_analysis.events, step_1.match_string1)
  AND REGEXP_CONTAINS(funnel_analysis.events, step_1.match_string2)
LIMIT
  500
```

Looking closely, most of the sequences found were inside the variations of the [engine_tab.foreground_metrics](https://dictionary.telemetry.mozilla.org/apps/fenix/metrics/engine_tab_foreground_metrics) event (currently corresponding to the `;` character), which does indeed have a lot of possible properties. We can make sure things like this aren't matched by putting a `(?:,|$)` at the end of the regular expression we're looking at, to ensure that we're genuinely at the end of an event sequence (indicated by a `,` or the end of the events_daily string).</strike>

**Comment by sean-rose** [comment]
This isn't fixed yet. #751 still needs to be merged.
