### ISSUE TITLE
Filter on `experiments` field for `client_counts`

### ISSUE THREAD

**Issue by rebecca-burwei** [mozilla/lookml-generator#321]
A follow-up to https://github.com/mozilla/lookml-generator/issues/310

Instead of creating a new explore for each nested field, could we make the nested fields filterable? For example, on the client_counts explore, return all rows that contained a `(key = 'firefox-suggest', value = 'treatment')` pair in the experiments field.

@scholtzan

**Comment by scholtzan** [comment]
It should already be possible to filter on nested fields, like experiment `key` and `value`: https://mozilla.cloud.looker.com/x/J4fQ8mVrZFDVw8g98Czif9 Or do you have a specific example of something that is currently not possible to express? 

We'll have to create a separate view for each repeated, nested field in order for the fields to get joined on to the existing explore.

**Comment by rebecca-burwei** [comment]
ah, thanks for the example. I didn't realize it was possible to use fields from different sections of the explore together. yes, this functionality is already available :)
