### ISSUE TITLE
Allow wildcard characters in namespace-disallowlist.yaml

### ISSUE THREAD

**Issue by scholtzan** [mozilla/lookml-generator#326]
Follow-up to https://github.com/mozilla/lookml-generator/pull/325#issuecomment-990373833

It should be possible to express something like the following in `namespace-disallowlist.yaml`:

```yaml
- rally-*
- pioneer-*
```

**Comment by Marlene-M-Hirose** [comment]
This has been done: https://github.com/mozilla/lookml-generator/pull/454
