### ISSUE TITLE
Remove logic for automatically generating namespace folders

### ISSUE THREAD

**Issue by scholtzan** [mozilla/lookml-generator#393]
Since we are now creating folders manually, we can stop generating folders for namespaces: https://github.com/mozilla/lookml-generator/blob/e47ff91b7352e31d0fcf443d1181f49336df6542/generator/content.py#L43
It's worth checking whether this method does something we want/need to keep doing or whether we can simply delete it

**Comment by Marlene-M-Hirose** [comment]
https://github.com/mozilla/lookml-generator/pull/423 - addresess this
