### ISSUE TITLE
Desync between BigQuery schemas and Probe Info Service causes invalid LookML for Glean ping Views/Explores

### ISSUE THREAD

**Issue by ANich** [mozilla/lookml-generator#412]
The lookml-generator currently uses the BigQuery schema to generate dimensions, but the Probe Info Service (via the `mozilla-schema-generator` package) to generated nested views for Glean ping Views. 

This means that whenever they're out of sync - for example if the `mozilla_schema_generator` task on Airflow is failing [example](https://bugzilla.mozilla.org/show_bug.cgi?id=1764332#c5) but a ping has been added and is visible in the Probe Info Service - the dimension won't be generated. 

Here's an example - The [Fenix Metrics Explore](https://github.com/mozilla/looker-hub/blob/0cc492901ec462eddb0940b72197ffba6f286466/fenix/explores/metrics.explore.lkml#L247-L260) is trying to join (unnest) a [nested View](https://github.com/mozilla/looker-hub/blob/0cc492901ec462eddb0940b72197ffba6f286466/fenix/views/metrics.view.lkml#L9262) (generated using the Probe Info Service), on a metric (`metrics__labeled_counter__recent_synced_tabs_recent_synced_tab_opened`) that didn't get generated because the BigQuery schema hasn't been updated. 

The Invalid LookML still gets generated on looker-hub though, which blocks LookML validation (and pull requests, etc.)

**Comment by scholtzan** [comment]
Temporary workaround. I added dummy values for the referenced fields: https://github.com/mozilla/looker-spoke-default/pull/300
