### ISSUE TITLE
Expose `url` types in Glean Ping views

### ISSUE THREAD

**Issue by fbertsch** [mozilla/lookml-generator#539]
The `url` type was added to the Glean client and is being used to send data for MDN, but this codebase doesn't propagate those fields to the Looker views. This ticket is for exposing them.

It should start with exposing them as `ALLOWED_TYPES` here (that might be everything, but also add a test).

**Comment by badboy** [comment]
the url metric is named `url2` in the tables. Is this something the generator has to deal with?
