### ISSUE TITLE
sync-dashboards-prod CI tasks failing due to timeout

### ISSUE THREAD

**Issue by scholtzan** [mozilla/lookml-generator#592]
The `sync-dashboard-prod` CI tasks have been failing due to a timeout for a while: https://circleci.com/gh/mozilla/looker-spoke-default/773

The simplest fix might be to just increase that timeout (I think we did so in the past).

cc @YeonjooSmith

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-634)

**Comment by YeonjooSmith** [comment]
Hello @scholtzan!
[The VPN dashboard in the shared folder](https://mozilla.cloud.looker.com/dashboards/413?Provider=&Pricing%20Plan=&Country=&Subscription%20Start%20Date=6%20month&Plan%20Interval%20Type=&Product%20Name=Mozilla%20VPN,Mozilla%20VPN%20%26%20Firefox%20Relay) is not sybced with [the dashboard in LookML Dashboards folder](https://mozilla.cloud.looker.com/dashboards/mozilla_vpn::vpn_saasboard__churn?Provider=&Pricing%20Plan=&Country=&Subscription%20Start%20Date=6%20month&Plan%20Interval%20Type=&Product%20Name=Mozilla%20VPN,Mozilla%20VPN%20%26%20Firefox%20Relay&Original%20Subscription%20Start%20Date=6%20month). 
Could you look into this issue again?

**Comment by scholtzan** [comment]
@fbertsch wanna increase the timeout even more?

**Comment by YeonjooSmith** [comment]
Hi @scholtzan , @fbertsch  
Would you please take a look at this bug again when you get a chance? It is still not fixed :(

**Comment by mikewilli** [comment]
I just took a quick look at this and it appears that the sync task in CI has been succeeding for the past couple weeks.

@YeonjooSmith Are you still seeing issues or can you confirm that they are fixed?

**Comment by scholtzan** [comment]
Yeah this got fixed a couple weeks ago in https://github.com/mozilla/looker-spoke-default/commit/22d4ac00896ccb2a9042f18b56dfc17b0910c4b5. Forgot to close this issue
