### ISSUE TITLE
Add links to Glean dictionary for Glean Ping explores

### ISSUE THREAD

**Issue by fbertsch** [mozilla/lookml-generator#64]
This should roughly match the [unified metrics](https://github.com/mozilla/looker-spoke-default/blob/main/firefox_ios/views/unified_metrics.view.lkml) view. All dimensions and measures that have an entry in the Glean dictionary should have a link to that entry.

**Comment by wlach** [comment]
Working on this, making progress but doing this "right" is more complicated than expected.
