### ISSUE TITLE
Create new `GleanPingView` and `GleanPingExplore` types

### ISSUE THREAD

**Issue by fbertsch** [mozilla/lookml-generator#67]
Glean Pings should be treated as special cases of structured ingestion ping tables. We know they have a specific shape, we understand what parts of the schema represent, and we can use metadata from probeinfo.tmo to make them more useful.

Specifically, this is for creating a new `GleanPingView` and `GleanPingExplore` that will do just that. We can start with simply creating those files, and replicating what we do with `PingView`, except limiting it to just Glean Apps and their ping tables.

From there, we can pull in data from `probeinfo.telemetry.mozilla.org` to add metadata to these. Some examples:
- Add these Glean Dictionary integration points
- Include descriptions from probeinfo.tmo
- Create per-category dropdowns as dimensions
- Create better dimensions for some Glean measures (e.g. timing distributions)

Most of the above should be done in follow-up issues, but this is for first creating new types that allow us to pull in probe-info-service.

**Comment by wlach** [comment]
@fbertsch It looks like we only create a `PingView` for glean apps at the moment. Maybe we should we just rename it to `GleanPingView` and punt the problem of how to deal with non-Glean data into the future?

**Comment by fbertsch** [comment]
@wlach it may look that way, but right now we only update `namespaces.yaml` for Glean apps. Non-glean namespaces use `custom-namespaces.yaml`. You can see there that DUET has e.g. [`new_profile` ping as a `PingView`](https://github.com/mozilla/lookml-generator/blob/main/custom-namespaces.yaml#L13-L17).

**Comment by wlach** [comment]
Working on this. I have the new types but I think we need to actually use them for something to validate the approach. Will land as part of  #64.
