### ISSUE TITLE
Mark `additional_properties` as hidden

### ISSUE THREAD

**Issue by fbertsch** [mozilla/lookml-generator#72]
We don't need to expose `additional_properties` to end users in Looker.

**Comment by tshrv** [comment]
Hey @fbertsch , I want to collaborate. Please tell me how to proceed.
Thanks.

**Comment by fbertsch** [comment]
Hi @tshrv, sure! For this issue, we want to mark any column called `additional_properties` as a hidden field. That would happen [in this function](https://github.com/mozilla/lookml-generator/blob/main/generator/views/lookml_utils.py#L34). Start by adding a test case [here](https://github.com/mozilla/lookml-generator/blob/main/tests/test_lookml.py#L60), where there should be a new schema field called `additional_properties` with a type of `STRING`. Please reach out if you have questions!

**Comment by tshrv** [comment]
Thanks @fbertsch . I'm working on it.

**Comment by fbertsch** [comment]
@tshrv Looking forward to seeing what you come up with. Again, let me know if you have any questions.

**Comment by tshrv** [comment]
Hi @fbertsch 

I've tried to follow what you said.
Added additional_properties to HIDDEN_DIMENSIONS at [lookml_utils.py:26](https://github.com/tshrv/lookml-generator/blob/ba42e44cf7f6551edf611dfbab34b0e0b94c027f/generator/views/lookml_utils.py#L26)
Added SchemaField of type STRING at [test_lookml.py:114](https://github.com/tshrv/lookml-generator/blob/ba42e44cf7f6551edf611dfbab34b0e0b94c027f/tests/test_lookml.py#L114)

**It fails a test case as there's a mismatch in the sequence**. The result has additional_properties in the beginning, making everything move one place further and causing the test to fail. Please look at the following logs -

```
FAILED tests/test_lookml.py::test_lookml_actual - AssertionError
Differences:
Expected=${TABLE}.client_info.client_id, Result=${TABLE}.additional_properties - .views.0.dimensions.0.sql
Expected=client_info__client_id, Result=additional_properties - .views.0.dimensions.0.name
In Expected, not in Result - .views.0.dimensions.1.type
In Expected, not in Result - .views.0.dimensions.1.group_item_label
In Expected, not in Result - .views.0.dimensions.1.map_layer_name
In Expected, not in Result - .views.0.dimensions.1.group_label
In Result, not in Expected - .views.0.dimensions.1.hidden
Expected=metadata__geo__country, Result=client_info__client_id - .views.0.dimensions.1.name
Expected=${TABLE}.metadata.geo.country, Result=${TABLE}.client_info.client_id - .views.0.dimensions.1.sql
In Result, not in Expected - .views.0.dimensions.2.map_layer_name
Expected=metadata__header__date, Result=metadata__geo__country - .views.0.dimensions.2.name
Expected=Metadata Header, Result=Metadata Geo - .views.0.dimensions.2.group_label
Expected=${TABLE}.metadata.header.date, Result=${TABLE}.metadata.geo.country - .views.0.dimensions.2.sql
Expected=Date, Result=Country - .views.0.dimensions.2.group_item_label
In Result, not in Expected - .views.0.dimensions.3.group_item_label
In Result, not in Expected - .views.0.dimensions.3.group_label
Expected=test_bignumeric, Result=metadata__header__date - .views.0.dimensions.3.name
Expected=${TABLE}.test_bignumeric, Result=${TABLE}.metadata.header.date - .views.0.dimensions.3.sql
Expected=test_bool, Result=test_bignumeric - .views.0.dimensions.4.name
Expected=yesno, Result=string - .views.0.dimensions.4.type
Expected=${TABLE}.test_bool, Result=${TABLE}.test_bignumeric - .views.0.dimensions.4.sql
Expected=test_bytes, Result=test_bool - .views.0.dimensions.5.name
Expected=string, Result=yesno - .views.0.dimensions.5.type
Expected=${TABLE}.test_bytes, Result=${TABLE}.test_bool - .views.0.dimensions.5.sql
Expected=test_float64, Result=test_bytes - .views.0.dimensions.6.name
Expected=number, Result=string - .views.0.dimensions.6.type
Expected=${TABLE}.test_float64, Result=${TABLE}.test_bytes - .views.0.dimensions.6.sql
Expected=test_int64, Result=test_float64 - .views.0.dimensions.7.name
Expected=${TABLE}.test_int64, Result=${TABLE}.test_float64 - .views.0.dimensions.7.sql
Expected=test_numeric, Result=test_int64 - .views.0.dimensions.8.name
Expected=${TABLE}.test_numeric, Result=${TABLE}.test_int64 - .views.0.dimensions.8.sql
Expected=test_string, Result=test_numeric - .views.0.dimensions.9.name
Expected=string, Result=number - .views.0.dimensions.9.type
Expected=${TABLE}.test_string, Result=${TABLE}.test_numeric - .views.0.dimensions.9.sql
Result contains extra element {'sql': '${TABLE}.test_string', 'type': 'string', 'name': 'test_string'} - .views.0.dimensions.10
```
I'm missing something here, can you please point it out?  Thanks.

**Comment by fbertsch** [comment]
@tshrv great work! Everything you've done so far is correct. For the final step you'll need to add that hidden dimension to the `expected` lookml [here](https://github.com/tshrv/lookml-generator/blob/ba42e44cf7f6551edf611dfbab34b0e0b94c027f/tests/test_lookml.py#L624). It should also be hidden.

**Comment by tshrv** [comment]
It passes all the test cases now. Thanks for your help @fbertsch. What's the next step?

**Comment by fbertsch** [comment]
@tshrv perfect! Go ahead and open a PR: https://github.com/mozilla/lookml-generator/pulls.
