### ISSUE TITLE
Expose unnested `events` views rather than ping tables

### ISSUE THREAD

**Issue by fbertsch** [mozilla/lookml-generator#94]
This depends on https://bugzilla.mozilla.org/show_bug.cgi?id=1710088#c5.

We want to do two things here:
1. Stop outputting an `events` `GleanPing` explore and view. The events `TableView` is fine.
2. Create a new view and explore that extends `GleanPing`, but is unnested events, rather than metrics and nested events. Initially this will be named `events_unnested` in BQ.
3. Eventually, transition `events_unnested` to replace `events`, and also transition this view definition to instead read from the `events` table

**Comment by fbertsch** [comment]
The above bug is complete. This issue is blocked on https://github.com/mozilla/lookml-generator/issues/156.

**Comment by wlach** [comment]
This was fixed a while ago.
