### ISSUE TITLE
Glean metric dimensions should not have type in their name

### ISSUE THREAD

**Issue by fbertsch** [mozilla/lookml-generator#99]
For Glean metric dimensions, we use both `label` and `name`. The `name` is generally hidden from end users, but it comes up in the table that is displayed after a query is run. We should change the name to roughly match the metric name. [Code here](https://github.com/mozilla/lookml-generator/blob/main/generator/views/glean_ping_view.py#L96).

**Comment by wlach** [comment]
The above link is out of date, here's an historical view of the file at the point that comment was made: https://github.com/mozilla/lookml-generator/blob/e36c290d994f3b01802a9d53a7424ba5f239c9a3/generator/views/glean_ping_view.py#L96

**Comment by wlach** [comment]
This does indeed look pretty silly:

![image](https://user-images.githubusercontent.com/20569/129741972-549e94c0-5b68-4111-b7d6-aeeaf6fc3837.png)
